### ISSUE TITLE
Status Code 401 <Unauthorized> on Login

### ISSUE THREAD

**Issue by Nicolas3347** [metasys-server/basic-services-dotnet#121]
Hi,
I try to used your code to connect to my client Metasys WebServer. I cannot pass this failure code 401 on the Login call.
Is there any specifics that need to be done on the server to pass this error and be able to login and than use all the other feature calls.
![error 401](https://user-images.githubusercontent.com/99502304/153646585-6a5f5a6f-4d17-41c3-8853-ac112d8488ef.png)

I used to work with the OLD MSSDA but need to upgrade. 

The Metasys server is on Computer 1 where my Application would be on Computer 2 however under the same private network.
Computer 1 (Metasys) has a certificat installed.

`Function: Login
Message: Call failed with status code 401 (Unauthorized): POST https://**********/api/v3/login
Source: MetasysServices
Trace:    at JohnsonControls.Metasys.BasicServices.BasicServiceProvider.ThrowHttpException(FlurlHttpException e)
   at JohnsonControls.Metasys.BasicServices.MetasysClient.<TryLoginAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JohnsonControls.Metasys.BasicServices.MetasysClient.TryLogin(String username, String password, Boolean refresh)`

`Function: sendCMD2Control
Message: Call failed with status code 401 (Unauthorized): GET https://*********/api/v3/objectIdentifiers?fqr=********%3ATDC1-NAE2BMA%2FProgramming.HVAC%20CALLS.Tower-6.T6-06HVAC%205525
Source: MetasysServices
Trace:    at JohnsonControls.Metasys.BasicServices.BasicServiceProvider.ThrowHttpException(FlurlHttpException e)
   at JohnsonControls.Metasys.BasicServices.MetasysClient.<GetObjectIdentifierAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JohnsonControls.Metasys.BasicServices.MetasysClient.GetObjectIdentifier(String itemReference)`

**Comment by michaelgwelch** [comment]
The biggest issues with login are

1. Not using a user with type API User
2. Not logging in to MUI or SMP with that account at least one time to accept terms and conditions.
